image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_USERNAME/coffee-project .
    - docker push $DOCKER_HUB_USERNAME/coffee-project

